# Generated by Django 5.1.3 on 2024-11-10 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('value', models.SmallIntegerField(db_column='value', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('amount', models.SmallIntegerField(db_column='product_amount')),
                ('comment', models.TextField(blank=True, db_column='comment', null=True)),
                ('date_time', models.DateTimeField(db_column='date_time')),
                ('total_price', models.DecimalField(db_column='total_price', decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=50)),
                ('last_name', models.CharField(db_column='last_name', max_length=50)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=20, unique=True)),
                ('email', models.EmailField(db_column='email', max_length=50, unique=True)),
                ('password', models.CharField(db_column='password', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('country', models.CharField(db_column='country', max_length=50)),
                ('city', models.CharField(db_column='city', max_length=50)),
                ('street', models.CharField(db_column='street', max_length=50)),
                ('order', models.ForeignKey(db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50, unique=True)),
                ('info', models.TextField(blank=True, db_column='info', null=True)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField(db_column='amount')),
                ('discount', models.ForeignKey(blank=True, db_column='discount_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.discount')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user'),
        ),
    ]
