version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    container_name: lab1_backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: lab1_frontend
