FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN python -m pip install --upgrade pip \
    && python -m pip install -r requirements.txt \
    && python -m pip install colorama coverage pytest pytest-asyncio 

COPY . .
COPY .coveragerc .

RUN mkdir -p /app/reports

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1
ENV PYTEST_ADDOPTS="--color=yes"

CMD ["sh", "-c", "\
coverage run --branch --source=/app --omit='*/main.py' -m pytest /app/tests \
--maxfail=1 --disable-warnings -v --color=yes && \
coverage xml -o /app/reports/coverage-report.xml"]
